[versions]
agp = "8.11.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.0"
constraintlayout = "2.2.1"
adapterGuava = "3.0.0"
converterGson = "3.0.0"
circleimageview = "3.1.0"
converterScalars = "3.0.0"
picasso = "2.71828"
uploadservice = "4.9.4"
lottie = "6.6.6"
shimmer = "0.5.0"
sonicWaterWaveAnimation = "2.0.1"
uploadserviceOkhttp = "4.9.4"
firebaseMessaging = "25.0.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
adapter-guava = { group = "com.squareup.retrofit2", name = "adapter-guava", version.ref = "adapterGuava" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }
converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "converterScalars" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }
uploadservice = { group = "net.gotev", name = "uploadservice", version.ref = "uploadservice" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer" }
sonic-water-wave-animation = { group = "com.github.orbitalsonic", name = "Sonic-Water-Wave-Animation", version.ref = "sonicWaterWaveAnimation" }
uploadservice-okhttp = { group = "net.gotev", name = "uploadservice-okhttp", version.ref = "uploadserviceOkhttp" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

